### PR TITLE
add function convert_model to convert a model for easy usage

### PR DESCRIPTION
**Pull request by DTennant**

### CODE REVIEW

**Comment by vacancy** [comment]
Hi @DTennant Thanks for the contributing! The utility function looks great to me!

I have a few minor questions/comments on the implementation.
1. Could you please add some documentation about this? Some docs for the function itself will be fine. Alternatively, it will be good to include some use case in the README file.
2. The code can be simplified by using some notations like:
```
for pth_module, sync_module in zip([BatchNorm1d, BatchNorm2d], [SyncBatchNorm1d, SyncBatchNorm2d]):
    if isinstance(module, pth_module):
        mod = sync_module
```
3. Is there specific reason for the line `del module`? It seems to me that the python gc will automatically delete this var if there is no further reference to it.

**Comment by DTennant** [comment]
Thanks for your kind review! @vacancy 

1. I add docs for the function, and a use case in README.md

2. Thanks for the advice, I already changed it

3. You are right, I delete this line in the new commit

**Review by vacancy — APPROVED** [review]
Clean and helpful utility function! Thanks for your contribution!

**Comment by vacancy** [comment]
Thanks for your contribution! Nice implementation. I have merged it to the master branch. I have also added your account to the contributor list.

**Pull request merged**
